name: SMSML CI Pipeline (MLflow Run)

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install library inti
          pip install mlflow==2.19.0 pandas scikit-learn matplotlib seaborn dagshub
          # Jika ada dependencies tambahan
          if [ -f MLProject/requirements.txt ]; then pip install -r MLProject/requirements.txt; fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Train Model using MLflow Run
        env:

          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |    
          mlflow run . --env-manager=local

      - name: Train Model using MLflow Run
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Cek apakah run_id.txt terbentuk
          if [ -f MLProject/run_id.txt ]; then
             RUN_ID=$(cat MLProject/run_id.txt)
             echo "Found Run ID: $RUN_ID"
             
             # Lokasi artifact model. Karena kita run local di runner,
             # path-nya ada di ./mlruns atau ./MLProject/mlruns
             
             # Tips: MLflow cukup pintar mencari run ID jika tracking URI sama.
             # Kita coba build langsung.
             
             mlflow models build-docker \
               -m "runs:/$RUN_ID/model" \
               -n "${{ secrets.DOCKER_USERNAME }}/smsml-submission:latest" \
               --enable-mlserver
               
             # Push ke Docker Hub
             docker push "${{ secrets.DOCKER_USERNAME }}/smsml-submission:latest"
             
          else
             echo "Error: run_id.txt tidak ditemukan. Pastikan modelling.py menyimpannya!"
             exit 1
          fi
